# Process04

import logging
from sqlalchemy import create_engine, text, DateTime
from db import get_engine
from config import STAGING_TABLE, FINAL_TABLE
import pandas as pd

# LOAD TO STAGING TABLE

STAGING_TABLE = STAGING_TABLE
FINAL_TABLE = FINAL_TABLE

def load_to_staging(df: pd.DataFrame, engine):
    logging.info("Loading data into staging table")

    # Selecting only date columns
    hs_v2_date_entered_cols = [c for c in df.columns if c.startswith("properties.hs_v2_date_entered_")]
    hs_v2_date_exited_cols = [c for c in df.columns if c.startswith("properties.hs_v2_date_exited_")]
    normal_date_entered_cols = [c for c in df.columns if c.startswith("properties.date_entered_")]
    normal_date_exited_cols = [c for c in df.columns if c.startswith("properties.date_exited_")]
    all_date_cols = hs_v2_date_entered_cols + hs_v2_date_exited_cols + normal_date_entered_cols + normal_date_exited_cols

    # Type mapping for other date columns
    dtype_map = {
        "archived_at": DateTime(),
        "created_at": DateTime(), 
        "updated_at": DateTime(),
        "properties.hs_lastmodifieddate": DateTime(),
        "properties.closedate": DateTime(),
        "properties.expected_ppa_signature": DateTime(),
        "properties.cp_issued": DateTime(),
        "properties.planned_date_of_invoicing": DateTime(),
    }

    # Type mapping for special date columns
    dtype_map.update({col: DateTime() for col in all_date_cols})

    df.to_sql(
        name=STAGING_TABLE,
        schema="dbo",
        con=engine,
        if_exists="append",
        index=False,
        dtype=dtype_map,
        chunksize=1000
    )

    df_sql = pd.read_sql_table(STAGING_TABLE, con=engine, schema="dbo")
    print(df_sql)
   
    logging.info("Staging load completed")

# MERGE INTO FINAL TABLE

def merge_to_final(engine):
    
    logging.info("Merging staging into final table")
     
    merge_sql = f"""
        MERGE dbo.{FINAL_TABLE} WITH (HOLDLOCK) AS tgt
        USING (
            SELECT * FROM 
                (
                    SELECT *,ROW_NUMBER() OVER (PARTITION BY id ORDER BY updated_at DESC
                ) AS rn
        FROM dbo.{STAGING_TABLE}
        ) s
        WHERE rn = 1
        ) AS src
        ON tgt.id = TRY_CAST(src.id AS BIGINT)

        WHEN MATCHED AND src.updated_at > tgt.updated_at THEN
            UPDATE SET
                tgt.[properties_with_history] = src.[properties_with_history],
                tgt.[associations] = src.[associations],
                tgt.[associated_company] = src.[properties.associated_company],
                tgt.[project_code] = src.[properties.project_code],
                tgt.[dealname] = src.[properties.dealname],
                tgt.[pipeline] = src.[properties.pipeline],
                tgt.[pipeline_name] = src.[pipeline_name],
                tgt.[dealstage] = src.[properties.dealstage],
                tgt.[stage_name] = src.[stage_name],
                tgt.[stage_order] = src.[stage_order],
                tgt.[ce_entity] = src.[properties.ce_entity],
                tgt.[business_unit] = src.[properties.business_unit],
                tgt.[business_line] = src.[properties.business_line],
                tgt.[project_country] = src.[properties.project_country],
                tgt.[project_province] = src.[properties.project_province],
                tgt.[ppa_capacity] = src.[properties.ppa_capacity],
                tgt.[final_capacity_in_kw] = src.[properties.final_capacity_in_kw],
                tgt.[capacity_in_kwp] = src.[properties.capacity_in_kwp],
                tgt.[capacity_in_mwp] = src.[properties.capacity_in_mwp],
                tgt.[hs_closed_amount] = src.[properties.hs_closed_amount],
                tgt.[probability_of_closing] = src.[properties.probability_of_closing],
                tgt.[hs_deal_stage_probability] = src.[properties.hs_deal_stage_probability],
                tgt.[technology] = src.[properties.technology],
                tgt.[mna_greenfield_brownfield] = src.[properties.ma_greenfield__brownfield],
                tgt.[growth_type] = src.[properties.growth_type],
                tgt.[type_of_project_surface_type] = src.[properties.type_of_project_surface_type__],
                tgt.[type_of_commitment] = src.[properties.type_of_commitment],
                tgt.[closed_lost_reason] = src.[properties.closed_lost_reason__dropdown_],
                tgt.[days_to_close] = src.[properties.days_to_close],
                tgt.[hs_is_closed] = src.[properties.hs_is_closed],
                tgt.[included_in_mis] = src.[properties.included_in_mis],
                tgt.[gps] = src.[properties.gps],
                tgt.[archived] = src.[archived],
                tgt.[archived_at] = src.[archived_at],
                tgt.[updated_at] = src.[updated_at],
                tgt.[hs_lastmodifieddate] = src.[properties.hs_lastmodifieddate],
                tgt.[closedate] = src.[properties.closedate],
                tgt.[date_expected_ppa_signature] = src.[properties.expected_ppa_signature],
                tgt.[date_cp_issued] = src.[properties.cp_issued],
                tgt.[date_of_invoicing_planned] = src.[properties.planned_date_of_invoicing],
                tgt.[date_entered_current_stage] = src.[properties.hs_v2_date_entered_current_stage],
                tgt.[date_entered_stage_potential_prospect] = src.[properties.date_entered_stage___potential_prospect],
                tgt.[date_entered_stage_early_development] = src.[properties.date_entered_stage___early_development],
                tgt.[date_entered_stage_mid_development] = src.[properties.date_entered_stage___mid_development],
                tgt.[date_entered_stage_ppa_1st_mark_up] = src.[properties.date_entered_stage___ppa_1st_mark_up],
                tgt.[date_entered_stage_project_approved] = src.[properties.date_entered_stage___project_approved],
                tgt.[date_entered_stage_advanced_development] = src.[properties.date_entered_stage___advanced_development],
                tgt.[date_entered_closing_advanced] = src.[properties.date_entered_closing_advanced],
                tgt.[date_entered_stage_under_construction] = src.[properties.date_entered_stage___under_construction],
                tgt.[date_entered_stage_operating] = src.[properties.date_entered_stage___operating],
                tgt.[date_entered_stage_ready_to_build] = src.[properties.date_entered_stage___ready_to_build],
                tgt.[date_entered_stage_testing] = src.[properties.date_entered_stage___testing],
                tgt.[date_entered_grid_checking_dpt] = src.[properties.date_entered_grid_checking_dpt],
                tgt.[date_entered_preliminary_assessment] = src.[properties.date_entered_preliminary_assessment],
                tgt.[date_entered_non_binding_offer_early] = src.[properties.date_entered_non_binding_offer_early],
                tgt.[date_entered_binding_offer_spa_mid] = src.[properties.date_entered_binding_offer_spa_mid],
                tgt.[date_entered_bid_submitted] = src.[properties.date_entered_bid_submitted],
                tgt.[date_entered_ppa_signed] = src.[properties.date_entered_ppa_signed],
                tgt.[date_entered_invoiced] = src.[properties.date_entered_invoiced],
                tgt.[date_entered_project_awarded] = src.[properties.date_entered_project_awarded],
                tgt.[date_entered_stage_closed_lost] = src.[properties.date_entered_stage___closed_lost],
                tgt.[date_exited_potential_prospect] = src.[properties.date_exited_potential_prospect],
                tgt.[date_exited_early_development] = src.[properties.date_exited_early_development],
                tgt.[date_exited_mid_development] = src.[properties.date_exited_mid_development],
                tgt.[date_exited_ppa_1st_mark_up] = src.[properties.date_exited_ppa_1st_mark_up],
                tgt.[date_exited_project_approved] = src.[properties.date_exited_project_approved],
                tgt.[date_exited_advanced_development] = src.[properties.date_exited_advanced_development],
                tgt.[date_exited_closing_advanced] = src.[properties.date_exited_closing_advanced],
                tgt.[date_exited_under_construction] = src.[properties.date_exited_under_construction],
                tgt.[date_exited_operating] = src.[properties.date_exited_operating],
                tgt.[date_exited_ready_to_build] = src.[properties.date_exited_ready_to_build],
                tgt.[date_exited_testing] = src.[properties.date_exited_testing],
                tgt.[date_exited_grid_checking_dpt] = src.[properties.date_exited_grid_checking_dpt],
                tgt.[date_exited_preliminary_assessment] = src.[properties.date_exited_preliminary_assessment],
                tgt.[date_exited_non_binding_offer_early] = src.[properties.date_exited_non_binding_offer_early],
                tgt.[date_exited_binding_offer_spa_mid] = src.[properties.date_exited_binding_offer_spa_mid],
                tgt.[date_exited_bid_submitted] = src.[properties.date_exited_bid_submitted],
                tgt.[date_exited_ppa_signed] = src.[properties.date_exited_ppa_signed],
                tgt.[date_exited_invoiced] = src.[properties.date_exited_invoiced],
                tgt.[date_exited_project_awarded] = src.[properties.date_exited_project_awarded], 
                tgt.[hs_date_entered_cni_solar_potential_prospect] = src.[properties.hs_v2_date_entered_172697438],
                tgt.[hs_date_entered_cni_solar_early_development] = src.[properties.hs_v2_date_entered_172697439],
                tgt.[hs_date_entered_cni_solar_mid_development] = src.[properties.hs_v2_date_entered_172697440],
                tgt.[hs_date_entered_cni_solar_ppa_1st_mark_up] = src.[properties.hs_v2_date_entered_172697441],
                tgt.[hs_date_entered_cni_solar_closed_lost] = src.[properties.hs_v2_date_entered_172697443],
                tgt.[hs_date_entered_cni_solar_project_approved] = src.[properties.hs_v2_date_entered_181472374],
                tgt.[hs_date_entered_cni_solar_advanced_development] = src.[properties.hs_v2_date_entered_183929950],
                tgt.[hs_date_entered_mna_spa_signed_advanced] = src.[properties.hs_v2_date_entered_3271943924],
                tgt.[hs_date_entered_engineering_invoiced] = src.[properties.hs_v2_date_entered_3275128565],
                tgt.[hs_date_entered_land_pipeline_deal_identification] = src.[properties.hs_v2_date_entered_947733654],
                tgt.[hs_date_entered_land_pipeline_advanced_development] = src.[properties.hs_v2_date_entered_947733655],
                tgt.[hs_date_entered_land_pipeline_mid_development] = src.[properties.hs_v2_date_entered_947733656],
                tgt.[hs_date_entered_land_pipeline_closed_lost] = src.[properties.hs_v2_date_entered_947761553],
                tgt.[hs_date_entered_grid_solutions_potential_prospect] = src.[properties.hs_v2_date_entered_953835685],
                tgt.[hs_date_entered_grid_solutions_early_development] = src.[properties.hs_v2_date_entered_953835686],
                tgt.[hs_date_entered_grid_solutions_mid_development] = src.[properties.hs_v2_date_entered_953835687],
                tgt.[hs_date_entered_grid_solutions_ppa_1st_mark_up] = src.[properties.hs_v2_date_entered_953835688],
                tgt.[hs_date_entered_grid_solutions_project_approved] = src.[properties.hs_v2_date_entered_953835689],
                tgt.[hs_date_entered_grid_solutions_closed_lost] = src.[properties.hs_v2_date_entered_953835691],
                tgt.[hs_date_entered_land_pipeline_early_development] = src.[properties.hs_v2_date_entered_953840641],
                tgt.[hs_date_entered_grid_solutions_advanced_development] = src.[properties.hs_v2_date_entered_962990195],
                tgt.[hs_date_entered_mna_preliminary_assessment] = src.[properties.hs_v2_date_entered_987141709],
                tgt.[hs_date_entered_mna_non_binding_offer_early] = src.[properties.hs_v2_date_entered_987141711],
                tgt.[hs_date_entered_mna_binding_offer_mid] = src.[properties.hs_v2_date_entered_987141713],
                tgt.[hs_date_entered_mna_closed] = src.[properties.hs_v2_date_entered_987141714],
                tgt.[hs_date_entered_mna_closed_lost] = src.[properties.hs_v2_date_entered_987141715],
                tgt.[hs_date_entered_engineering_ready_to_build] = src.[properties.hs_v2_date_entered_989326996],
                tgt.[hs_date_entered_engineering_under_construction] = src.[properties.hs_v2_date_entered_989326997],
                tgt.[hs_date_entered_engineering_energized] = src.[properties.hs_v2_date_entered_989326998],
                tgt.[hs_date_entered_engineering_cod] = src.[properties.hs_v2_date_entered_989326999],
                tgt.[hs_date_entered_engineering_advanced_development] = src.[properties.hs_v2_date_entered_997789966],
                tgt.[hs_date_exited_cni_solar_potential_prospect] = src.[properties.hs_v2_date_exited_172697438],
                tgt.[hs_date_exited_cni_solar_early_development] = src.[properties.hs_v2_date_exited_172697439],
                tgt.[hs_date_exited_cni_solar_mid_development] = src.[properties.hs_v2_date_exited_172697440],
                tgt.[hs_date_exited_cni_solar_ppa_1st_mark_up] = src.[properties.hs_v2_date_exited_172697441],
                tgt.[hs_date_exited_cni_solar_closed_lost] = src.[properties.hs_v2_date_exited_172697443],
                tgt.[hs_date_exited_cni_solar_project_approved] = src.[properties.hs_v2_date_exited_181472374],
                tgt.[hs_date_exited_cni_solar_advanced_development] = src.[properties.hs_v2_date_exited_183929950],
                tgt.[hs_date_exited_mna_spa_signed_advanced] = src.[properties.hs_v2_date_exited_3271943924],
                tgt.[hs_date_exited_engineering_invoiced] = src.[properties.hs_v2_date_exited_3275128565],
                tgt.[hs_date_exited_land_pipeline_deal_identification] = src.[properties.hs_v2_date_exited_947733654],
                tgt.[hs_date_exited_land_pipeline_advanced_development] = src.[properties.hs_v2_date_exited_947733655],
                tgt.[hs_date_exited_land_pipeline_mid_development] = src.[properties.hs_v2_date_exited_947733656],
                tgt.[hs_date_exited_land_pipeline_closed_lost] = src.[properties.hs_v2_date_exited_947761553],
                tgt.[hs_date_exited_grid_solutions_potential_prospect] = src.[properties.hs_v2_date_exited_953835685],
                tgt.[hs_date_exited_grid_solutions_early_development] = src.[properties.hs_v2_date_exited_953835686],
                tgt.[hs_date_exited_grid_solutions_mid_development] = src.[properties.hs_v2_date_exited_953835687],
                tgt.[hs_date_exited_grid_solutions_ppa_1st_mark_up] = src.[properties.hs_v2_date_exited_953835688],
                tgt.[hs_date_exited_grid_solutions_project_approved] = src.[properties.hs_v2_date_exited_953835689],
                tgt.[hs_date_exited_grid_solutions_closed_lost] = src.[properties.hs_v2_date_exited_953835691],
                tgt.[hs_date_exited_land_pipeline_early_development] = src.[properties.hs_v2_date_exited_953840641],
                tgt.[hs_date_exited_grid_solutions_advanced_development] = src.[properties.hs_v2_date_exited_962990195],
                tgt.[hs_date_exited_mna_preliminary_assessment] = src.[properties.hs_v2_date_exited_987141709],
                tgt.[hs_date_exited_mna_non_binding_offer_early] = src.[properties.hs_v2_date_exited_987141711],
                tgt.[hs_date_exited_mna_binding_offer_mid] = src.[properties.hs_v2_date_exited_987141713],
                tgt.[hs_date_exited_mna_closed] = src.[properties.hs_v2_date_exited_987141714],
                tgt.[hs_date_exited_mna_closed_lost] = src.[properties.hs_v2_date_exited_987141715],
                tgt.[hs_date_exited_engineering_ready_to_build] = src.[properties.hs_v2_date_exited_989326996],
                tgt.[hs_date_exited_engineering_under_construction] = src.[properties.hs_v2_date_exited_989326997],
                tgt.[hs_date_exited_engineering_energized] = src.[properties.hs_v2_date_exited_989326998],
                tgt.[hs_date_exited_engineering_cod] = src.[properties.hs_v2_date_exited_989326999],
                tgt.[hs_date_exited_engineering_advanced_development] = src.[properties.hs_v2_date_exited_997789966]
        WHEN NOT MATCHED
        AND TRY_CAST(src.id AS BIGINT) IS NOT NULL THEN
            INSERT (
                [id],
                [object_write_trace_id],
                [properties_with_history],
                [associations],
                [associated_company],
                [project_code],
                [dealname],
                [pipeline],
                [pipeline_name],
                [dealstage],
                [stage_name],
                [stage_order],
                [ce_entity],
                [business_unit],
                [business_line],
                [project_country],
                [project_province],
                [ppa_capacity],
                [final_capacity_in_kw],
                [capacity_in_kwp],
                [capacity_in_mwp],
                [hs_closed_amount],
                [probability_of_closing],
                [hs_deal_stage_probability],
                [technology],
                [mna_greenfield_brownfield],
                [growth_type],
                [type_of_project_surface_type],
                [type_of_commitment],
                [closed_lost_reason],
                [days_to_close],
                [hs_is_closed],
                [included_in_mis],
                [gps],
                [archived],
                [archived_at],
                [created_at],
                [updated_at],
                [hs_lastmodifieddate],
                [closedate],
                [date_expected_ppa_signature],
                [date_cp_issued],
                [date_of_invoicing_planned],
                [date_entered_current_stage],
                [date_entered_stage_potential_prospect],
                [date_entered_stage_early_development],
                [date_entered_stage_mid_development],
                [date_entered_stage_ppa_1st_mark_up],
                [date_entered_stage_project_approved],
                [date_entered_stage_advanced_development],
                [date_entered_closing_advanced],
                [date_entered_stage_under_construction],
                [date_entered_stage_operating],
                [date_entered_stage_ready_to_build],
                [date_entered_stage_testing],
                [date_entered_grid_checking_dpt],
                [date_entered_preliminary_assessment],
                [date_entered_non_binding_offer_early],
                [date_entered_binding_offer_spa_mid],
                [date_entered_bid_submitted],
                [date_entered_ppa_signed],
                [date_entered_invoiced],
                [date_entered_project_awarded],
                [date_entered_stage_closed_lost],
                [date_exited_potential_prospect],
                [date_exited_early_development],
                [date_exited_mid_development],
                [date_exited_ppa_1st_mark_up],
                [date_exited_project_approved],
                [date_exited_advanced_development],
                [date_exited_closing_advanced],
                [date_exited_under_construction],
                [date_exited_operating],
                [date_exited_ready_to_build],
                [date_exited_testing],
                [date_exited_grid_checking_dpt],
                [date_exited_preliminary_assessment],
                [date_exited_non_binding_offer_early],
                [date_exited_binding_offer_spa_mid], 
                [date_exited_bid_submitted],
                [date_exited_ppa_signed],
                [date_exited_invoiced],
                [date_exited_project_awarded],
                [hs_date_entered_cni_solar_potential_prospect],
                [hs_date_entered_cni_solar_early_development],
                [hs_date_entered_cni_solar_mid_development],
                [hs_date_entered_cni_solar_ppa_1st_mark_up],
                [hs_date_entered_cni_solar_closed_lost],
                [hs_date_entered_cni_solar_project_approved],
                [hs_date_entered_cni_solar_advanced_development],
                [hs_date_entered_mna_spa_signed_advanced],
                [hs_date_entered_engineering_invoiced],
                [hs_date_entered_land_pipeline_deal_identification],
                [hs_date_entered_land_pipeline_advanced_development],
                [hs_date_entered_land_pipeline_mid_development],
                [hs_date_entered_land_pipeline_closed_lost],
                [hs_date_entered_grid_solutions_potential_prospect],
                [hs_date_entered_grid_solutions_early_development],
                [hs_date_entered_grid_solutions_mid_development],
                [hs_date_entered_grid_solutions_ppa_1st_mark_up],
                [hs_date_entered_grid_solutions_project_approved],
                [hs_date_entered_grid_solutions_closed_lost],
                [hs_date_entered_land_pipeline_early_development],
                [hs_date_entered_grid_solutions_advanced_development],
                [hs_date_entered_mna_preliminary_assessment],
                [hs_date_entered_mna_non_binding_offer_early],
                [hs_date_entered_mna_binding_offer_mid],
                [hs_date_entered_mna_closed],
                [hs_date_entered_mna_closed_lost],
                [hs_date_entered_engineering_ready_to_build],
                [hs_date_entered_engineering_under_construction],
                [hs_date_entered_engineering_energized],
                [hs_date_entered_engineering_cod],
                [hs_date_entered_engineering_advanced_development],
                [hs_date_exited_cni_solar_potential_prospect],
                [hs_date_exited_cni_solar_early_development],
                [hs_date_exited_cni_solar_mid_development],
                [hs_date_exited_cni_solar_ppa_1st_mark_up],
                [hs_date_exited_cni_solar_closed_lost],
                [hs_date_exited_cni_solar_project_approved],
                [hs_date_exited_cni_solar_advanced_development],
                [hs_date_exited_mna_spa_signed_advanced],
                [hs_date_exited_engineering_invoiced],
                [hs_date_exited_land_pipeline_deal_identification],
                [hs_date_exited_land_pipeline_advanced_development],
                [hs_date_exited_land_pipeline_mid_development],
                [hs_date_exited_land_pipeline_closed_lost],
                [hs_date_exited_grid_solutions_potential_prospect],
                [hs_date_exited_grid_solutions_early_development],
                [hs_date_exited_grid_solutions_mid_development],
                [hs_date_exited_grid_solutions_ppa_1st_mark_up],
                [hs_date_exited_grid_solutions_project_approved],
                [hs_date_exited_grid_solutions_closed_lost],
                [hs_date_exited_land_pipeline_early_development],
                [hs_date_exited_grid_solutions_advanced_development],
                [hs_date_exited_mna_preliminary_assessment],
                [hs_date_exited_mna_non_binding_offer_early],
                [hs_date_exited_mna_binding_offer_mid],
                [hs_date_exited_mna_closed],
                [hs_date_exited_mna_closed_lost],
                [hs_date_exited_engineering_ready_to_build],
                [hs_date_exited_engineering_under_construction],
                [hs_date_exited_engineering_energized],
                [hs_date_exited_engineering_cod],
                [hs_date_exited_engineering_advanced_development]
            )
            VALUES (
                TRY_CAST(src.[id] AS BIGINT),
                src.[object_write_trace_id],
                src.[properties_with_history],
                src.[associations],
                src.[properties.associated_company],
                src.[properties.project_code],
                src.[properties.dealname],
                src.[properties.pipeline],
                src.[pipeline_name],
                src.[properties.dealstage],
                src.[stage_name],
                src.[stage_order],
                src.[properties.ce_entity],
                src.[properties.business_unit],
                src.[properties.business_line],
                src.[properties.project_country],
                src.[properties.project_province],
                src.[properties.ppa_capacity],
                src.[properties.final_capacity_in_kw],
                src.[properties.capacity_in_kwp],
                src.[properties.capacity_in_mwp],
                src.[properties.hs_closed_amount],
                src.[properties.probability_of_closing],
                src.[properties.hs_deal_stage_probability],
                src.[properties.technology],
                src.[properties.ma_greenfield__brownfield],
                src.[properties.growth_type],
                src.[properties.type_of_project_surface_type__],
                src.[properties.type_of_commitment],
                src.[properties.closed_lost_reason__dropdown_],
                src.[properties.days_to_close],
                src.[properties.hs_is_closed],
                src.[properties.included_in_mis],
                src.[properties.gps],
                src.[archived],
                src.[archived_at],
                src.[created_at],
                src.[updated_at],
                src.[properties.hs_lastmodifieddate],
                src.[properties.closedate],
                src.[properties.expected_ppa_signature],
                src.[properties.cp_issued],
                src.[properties.planned_date_of_invoicing],
                src.[properties.hs_v2_date_entered_current_stage],
                src.[properties.date_entered_stage___potential_prospect],
                src.[properties.date_entered_stage___early_development],
                src.[properties.date_entered_stage___mid_development],
                src.[properties.date_entered_stage___ppa_1st_mark_up],
                src.[properties.date_entered_stage___project_approved],
                src.[properties.date_entered_stage___advanced_development],
                src.[properties.date_entered_closing_advanced],                
                src.[properties.date_entered_stage___under_construction],
                src.[properties.date_entered_stage___operating],
                src.[properties.date_entered_stage___ready_to_build],
                src.[properties.date_entered_stage___testing],
                src.[properties.date_entered_grid_checking_dpt],
                src.[properties.date_entered_preliminary_assessment],
                src.[properties.date_entered_non_binding_offer_early],
                src.[properties.date_entered_binding_offer_spa_mid],
                src.[properties.date_entered_bid_submitted],
                src.[properties.date_entered_ppa_signed],
                src.[properties.date_entered_invoiced],
                src.[properties.date_entered_project_awarded], 
                src.[properties.date_entered_stage___closed_lost],
                src.[properties.date_exited_potential_prospect],
                src.[properties.date_exited_early_development],
                src.[properties.date_exited_mid_development],
                src.[properties.date_exited_ppa_1st_mark_up],
                src.[properties.date_exited_project_approved],
                src.[properties.date_exited_advanced_development],
                src.[properties.date_exited_closing_advanced],
                src.[properties.date_exited_under_construction],
                src.[properties.date_exited_operating],
                src.[properties.date_exited_ready_to_build],
                src.[properties.date_exited_testing],
                src.[properties.date_exited_grid_checking_dpt],
                src.[properties.date_exited_preliminary_assessment],
                src.[properties.date_exited_non_binding_offer_early],
                src.[properties.date_exited_binding_offer_spa_mid], 
                src.[properties.date_exited_bid_submitted],
                src.[properties.date_exited_ppa_signed],
                src.[properties.date_exited_invoiced],
                src.[properties.date_exited_project_awarded],
                src.[properties.hs_v2_date_entered_172697438],
                src.[properties.hs_v2_date_entered_172697439],
                src.[properties.hs_v2_date_entered_172697440],
                src.[properties.hs_v2_date_entered_172697441],
                src.[properties.hs_v2_date_entered_172697443],
                src.[properties.hs_v2_date_entered_181472374],
                src.[properties.hs_v2_date_entered_183929950],
                src.[properties.hs_v2_date_entered_3271943924],
                src.[properties.hs_v2_date_entered_3275128565],
                src.[properties.hs_v2_date_entered_947733654],
                src.[properties.hs_v2_date_entered_947733655],
                src.[properties.hs_v2_date_entered_947733656],
                src.[properties.hs_v2_date_entered_947761553],
                src.[properties.hs_v2_date_entered_953835685],
                src.[properties.hs_v2_date_entered_953835686],
                src.[properties.hs_v2_date_entered_953835687],
                src.[properties.hs_v2_date_entered_953835688],
                src.[properties.hs_v2_date_entered_953835689],
                src.[properties.hs_v2_date_entered_953835691],
                src.[properties.hs_v2_date_entered_953840641],
                src.[properties.hs_v2_date_entered_962990195],
                src.[properties.hs_v2_date_entered_987141709],
                src.[properties.hs_v2_date_entered_987141711],
                src.[properties.hs_v2_date_entered_987141713],
                src.[properties.hs_v2_date_entered_987141714],
                src.[properties.hs_v2_date_entered_987141715],
                src.[properties.hs_v2_date_entered_989326996],
                src.[properties.hs_v2_date_entered_989326997],
                src.[properties.hs_v2_date_entered_989326998],
                src.[properties.hs_v2_date_entered_989326999],
                src.[properties.hs_v2_date_entered_997789966],
                src.[properties.hs_v2_date_exited_172697438],
                src.[properties.hs_v2_date_exited_172697439],
                src.[properties.hs_v2_date_exited_172697440],
                src.[properties.hs_v2_date_exited_172697441],
                src.[properties.hs_v2_date_exited_172697443],
                src.[properties.hs_v2_date_exited_181472374],
                src.[properties.hs_v2_date_exited_183929950],
                src.[properties.hs_v2_date_exited_3271943924],
                src.[properties.hs_v2_date_exited_3275128565],
                src.[properties.hs_v2_date_exited_947733654],
                src.[properties.hs_v2_date_exited_947733655],
                src.[properties.hs_v2_date_exited_947733656],
                src.[properties.hs_v2_date_exited_947761553],
                src.[properties.hs_v2_date_exited_953835685],
                src.[properties.hs_v2_date_exited_953835686],
                src.[properties.hs_v2_date_exited_953835687],
                src.[properties.hs_v2_date_exited_953835688],
                src.[properties.hs_v2_date_exited_953835689],
                src.[properties.hs_v2_date_exited_953835691],
                src.[properties.hs_v2_date_exited_953840641],
                src.[properties.hs_v2_date_exited_962990195],
                src.[properties.hs_v2_date_exited_987141709],
                src.[properties.hs_v2_date_exited_987141711],
                src.[properties.hs_v2_date_exited_987141713],
                src.[properties.hs_v2_date_exited_987141714],
                src.[properties.hs_v2_date_exited_987141715],
                src.[properties.hs_v2_date_exited_989326996],
                src.[properties.hs_v2_date_exited_989326997],
                src.[properties.hs_v2_date_exited_989326998],
                src.[properties.hs_v2_date_exited_989326999],
                src.[properties.hs_v2_date_exited_997789966]
            );
     """

    with engine.begin() as conn:
        conn.execute(text(merge_sql))

    logging.info("Merge completed")